config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'profiles#dashboard'
  get 'comparison', to: 'profiles#comparison'
  get 'styleguide', to: "pages#styleguide"
  resources :appliances, only: :index
  resources :components, only: :index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :builds, only: [ :index, :show, :new, :create ] do
    resources :bookmarks, only: [ :create ]
  end
end

app/models/build.rb
class Build < ApplicationRecord
  belongs_to :battery
  belongs_to :solar_panel
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :build_appliances, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :appliances, through: :build_appliances
  accepts_nested_attributes_for :build_appliances, reject_if: :all_blank

  validates :name, presence: true, length: { maximum: 13 }

  def set_total_price
    self.total_price = appliances.sum(:price).to_i
  end

  def total_amp_hours
    build_appliances.sum(:amp_hours)
  end

  def fridge_use_hours
    build_appliances.joins(:appliance).where(appliances: { kind: "fridge" }).sum(:use_hours)
  end

  def fridge_amp_hours
    build_appliances.joins(:appliance).where(appliances: { kind: "fridge" }).sum(:amp_hours)
  end

  def lights_use_hours
    build_appliances.joins(:appliance).where(appliances: { kind: "lights" }).sum(:use_hours)
  end

  def lights_amp_hours
    build_appliances.joins(:appliance).where(appliances: { kind: "lights" }).sum(:amp_hours)
  end

  def fan_use_hours
    build_appliances.joins(:appliance).where(appliances: { kind: "fan" }).sum(:use_hours)
  end

  def fan_amp_hours
    build_appliances.joins(:appliance).where(appliances: { kind: "fan" }).sum(:amp_hours)
  end

  def inverter_use_hours
    build_appliances.joins(:appliance).where(appliances: { kind: "inverter" }).sum(:use_hours)
  end

  def inverter_amp_hours
    build_appliances.joins(:appliance).where(appliances: { kind: "inverter" }).sum(:amp_hours)
  end

  def pump_use_hours
    build_appliances.joins(:appliance).where(appliances: { kind: "pump" }).sum(:use_hours)
  end

  def pump_amp_hours
    build_appliances.joins(:appliance).where(appliances: { kind: "pump" }).sum(:amp_hours)
  end

  def charger_use_hours
    build_appliances.joins(:appliance).where(appliances: { kind: "charger" }).sum(:use_hours)
  end

  def charger_amp_hours
    build_appliances.joins(:appliance).where(appliances: { kind: "charger" }).sum(:amp_hours)
  end

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name ],
    associated_against: {
      user: [ :first_name, :last_name ],
      appliances: [ :kind ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]

  def index
    # @params_query = params[:query] && params[:query][:search_word] ? params[:query][:search_word] : ""
    if params[:query].present? && params[:query][:search_word].present?
      @params_query = params[:query][:search_word]
      @builds = Build.global_search(params[:query][:search_word])
    else
      @builds = Build.includes(:solar_panel, :battery, :user, :build_appliances)
    end
  end

  def show
    @build = Build.find(params[:id])
  end

  def new
    @build = Build.new
    @build.build_appliances.build
  end

  def create
    @build = Build.new(build_params)
    @build.user_id = current_user.id
    if @build.save
      @build.update(total_price: @build.set_total_price)
         # Will raise ActiveModel::ForbiddenAttributesError
      # flash[:alert] = "Your build #{@build.name} has been added to your Dashboard!"
      redirect_to build_path(@build)
    else
      flash[:alert] = "Error #{@build.errors.objects.first.full_message}"
      render :new
    end
  end

  private

  def build_params
    params.require(:build).permit(:name, :battery_id, :solar_panel_id, build_appliances_attributes: [:appliance_id, :use_hours])
  end
end

app/views/builds/index.html.erb
<div class="page-headers d-flex justify-content-between">
<% if params[:query].present? && params[:query][:search_word].present? %>
  <div class="index-results">
  <h1>Explore Builds</h1>
  <p> Showing <%= @builds.length %> results for  <span class="text-warning"> '<%= @params_query %>' </span></p>
  </div>
<% else %>
  <h1>Explore Builds</h1>
<% end %>
  <%= simple_form_for :query, url: builds_path, method: :get do |f| %>
    <div class="d-flex align-items-center position-relative">
      <%= f.input :search_word, placeholder: "Search by build name, appliance or creator name...", label: false, required: false, input_html: { value: @params_query, class: "search-field"}, wrapper_html: { class: "no-margin" } %>
      <div class="icon-positioning">
        <span class="material-symbols-outlined icon-circle text-white">search</span>
      </div>
    </div>
  <% end %>
</div>
<div class="cards-new card-wrapper-index">
  <% @builds.each do |build| %>
    <%= render "shared/build_card", build: build, appliances: build.appliances %>
  <% end %>
</div>

app/views/builds/show.html.erb
<div class="page-headers d-flex justify-content-between">
  <h1><%= @build.name.capitalize %></h1>
  <%# use '&' to sort out the case of not logged in. Alternatively wrap code in an 'if' to check whether logged in %>
  <% bookmark = current_user&.bookmarks&.find_by(build: @build) %>
  <% unless @build.user == current_user %>
    <% if bookmark.present? %>
      <p class="bookmarked">Added to bookmarks ♥</p>
    <% else %>
      <%# don't forget to specify 'method: :post' - the route uses POST %>
      <%= link_to "Add to bookmarks ♡", build_bookmarks_path(@build), method: :post, class: "bookmark-text" %>
    <% end %>
  <% end %>
</div>
<div class="card-wrapper-new mb-3">
  <div>
    <h2 class="mb-3">Appliances</h2>
    <div class="card-space card-grid">
      <% @build.appliances.each_with_index do |appliance, index|%>
        <%= render "shared/appliance_card_redesigned", appliance: appliance %>
      <% end %>
    </div>

    <h2 class="mt-5 mb-3">Components</h2>
    <div class="card-space card-grid">
      <div>
        <%= render "shared/battery_card_redesigned", battery: @build.battery %>
      </div>
      <div>
        <%= render "shared/solar_panel_card_redesigned", solar_panel: @build.solar_panel %>
      </div>
    </div>
  </div>
  <div class="sidebar-overview">
    <%= render "shared/overview_card" %>
  </div>
</div>