config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'profiles#dashboard'
  get 'comparison', to: 'profiles#comparison'
  get 'styleguide', to: "pages#styleguide"
  resources :appliances, only: :index
  resources :components, only: :index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :builds, only: [ :index, :show, :new, :create ] do
    resources :bookmarks, only: [ :create ]
  end
end

app/views/shared/_appliance_card.html.erb
<div class="builds-card-container">
  <div class="d-flex justify-content-around inner-space">
    <div>
      <div class="appliance-title">
        <%# <p><strong>Dometic</strong></p> %>
        <p><strong><%= appliance.make %></strong></p>
      </div>
      <div class="appliance-model">
        <%# <p><strong>RM8400</strong></p> %>
        <p><strong><%= appliance.model %></strong></p>
      </div>
      <div class="appliance-price">
        <%# <p class="mt-3"><strong>$300</strong></p> %>
        <p><strong><%= appliance.price %></strong></p>
      </div>
    </div>
    <%= image_tag "img#{rand(1..3)}.png" %>
  </div>
  <div class="build-text text-center mt-1">
    <p><strong>Volts:</strong> 12V   /  <strong>Amps:</strong> 0.5A</p>
  </div>
  <div class="build-link text-center mt-2">
    <a href="#">Go to product page</a>
  </div>
</div>

app/views/shared/_appliance_card_redesigned.html.erb
<div class="builds-card-container-new card-shadow box-relative">
  <div class="d-flex justify-content-between">
    <div>
      <div class="build-title-new align-items-start flex-column">
        <p class="mb-2 build-title-new"><%= appliance.model %></p>
        <p class="appliances-text mb-1"><%= appliance.make %></p>
      </div>
    </div>
    <%= image_tag "new_#{appliance.kind}_#{appliance.model.gsub(/\s+/, "").downcase}.png", class: "appliance-img"%>
  </div>
  <div class="d-flex mt-5">
    <span class="material-symbols-outlined me-1" style="color: gray;">open_in_new</span>
    <a href="www.duduckgo.com" class="appliances-text mt-1" style="text-decoration: none">Go to product page</a>
  </div>
  <div class="appliances-text d-flex border-top card-bottom-boxes-position w-100">
    <div class="d-flex flex-column w-100 right-border ps-3">
      <p class="mb-2 pt-2">Volts</p>
      <p class="text-black"><strong><%= appliance.voltage %> V</p> </strong>
    </div>
    <div class="d-flex flex-column w-100 ps-3 right-border">
      <p class="mb-2 pt-2">Amps</p>
      <p class="text-black"><strong><%= appliance.amps %> Ah</p> </strong>
    </div>
    <div class="d-flex flex-column w-100 ps-3">
      <p class="mb-2 pt-2">Price</p>
      <p class="text-black"><strong>$ <%= appliance.price %></p> </strong>
    </div>
  </div>
</div>

app/views/shared/_appliances_card.html.erb
<% @build.appliances.each_with_index do |appliance, index|%>
        <div class="builds-card-container">
          <div class="d-flex justify-content-around inner-space">
            <div>
              <div class="appliance-title">
                <%# <p><strong>Dometic</strong></p> %>
                <p><strong><%= appliance.make %></strong></p>
              </div>
              <div class="appliance-model">
                <%# <p><strong>RM8400</strong></p> %>
                <p><strong><%= appliance.model %></strong></p>
              </div>
              <div class="appliance-price">
                <%# <p class="mt-3"><strong>$300</strong></p> %>
                <p><strong><%= appliance.price %></strong></p>
              </div>
            </div>
            <%= image_tag "img#{rand(1..3)}.png" %>
          </div>
          <div class="build-text text-center mt-1">
            <p><strong>Volts:</strong> 12V   /  <strong>Amps:</strong> 0.5A</p>
          </div>
          <div class="build-link text-center mt-2">
            <a href="#">Go to product page</a>
          </div>
        </div>
      <% end %>

app/views/shared/_battery_card.html.erb
<div class="builds-card-container">
  <div class="d-flex justify-content-between inner-space">
    <div>
      <div class="build-title">
        <p><strong><%= build.battery.model %></strong></p>
      </div>
      <div class="build-model">
        <p><strong><%= build.battery.make %></strong></p>
      </div>
      <div class="build-price">
        <p class="mt-3"><strong>$ <%= build.battery.price %></strong></p>
      </div>
    </div>
    <%= image_tag "battery_color.png" %>
  </div>
  <div class="build-text text-center mt-1">
    <p><strong>Volts: <%= build.battery.voltage %>/ Amps: <%= build.battery.amp_hours %></strong></p>
  </div>
  <div class="build-link text-center mt-2">
    <a href="#">Go to product page</a>
  </div>
</div>

app/views/shared/_battery_card_redesigned.html.erb
<div class="builds-card-container-new card-shadow box-relative">
  <div class="d-flex justify-content-between">
    <div>
      <div class="build-title-new align-items-start flex-column">
        <p class="mb-2"><%= battery.model %></p>
        <p class="appliances-text mb-1"><%= battery.make %></p>
      </div>
    </div>
    <div>
      <%= image_tag "new_battery_#{battery.model.gsub(/\s+/, "").downcase}.png", class: "battery-img"%>
    </div>
  </div>
  <div class="d-flex mt-5">
    <span class="material-symbols-outlined" style="color: gray;">open_in_new</span>
    <a class="appliances-text mt-1" href="#" target="blank" class="appliances-text" style="text-decoration: none">Go to product page</a>
  </div>
  <div class="appliances-text d-flex border-top card-bottom-boxes-position w-100">
    <div class="d-flex flex-column w-100 right-border ps-3">
      <p class="mb-2 pt-2">Volts</p>
      <p class="text-black"> <strong><%= battery.voltage %> V</p></strong>
    </div>
    <div class="d-flex flex-column w-100 ps-3 right-border">
      <p class="mb-2 pt-2">Amp hours</p>
      <p class="text-black"> <strong><%= battery.amp_hours %> Ah</p></strong>
    </div>
    <div class="d-flex flex-column w-100 ps-3">
      <p class="mb-2 pt-2">Price</p>
      <p class="text-black"><strong>$ <%= battery.price %></p></strong>
    </div>
  </div>
</div>

app/views/shared/_build_card.html.erb
      <%= link_to build_path(build), class: "text-decoration-none text-black", target: :_blank do %>
        <div class="builds-card-container-new card-shadow box-relative">
          <div class="d-flex justify-content-between">
            <div>
              <div class="build-title-new">
                <p class="mb-1"><%= build.name %></p>
              </div>
            </div>
            <% if build.user.user_url != nil %>
            <%= image_tag build.user.user_url, class: "avatar-large", alt: "avatar-large" %>
            <%  else %>
            <%= cl_image_tag build.user.photo.key, class: "avatar-large", alt: "avatar-large"%>
            <% end%>
          </div>
          <p class="appliances-text mb-2">Appliances</p>
          <div class="d-flex" style="flex-wrap: wrap">
            <% appliances.each do |appliance| %>
              <% if appliance.kind == "inverter" %>
                <div class="pill-container me-1 mb-1">
                  <span class="pill-font"> 🔌 inverter</span>
                </div>
              <% elsif appliance.kind == "lights"%>
                <div class="pill-container me-1 mb-1">
                  <span class="pill-font"> 💡 lights</span>
                </div>
              <% elsif appliance.kind == "fridge"%>
                <div class="pill-container me-1 mb-1">
                  <span class="pill-font"> ❄️ fridge</span>
                </div>
              <% elsif appliance.kind == "fan"%>
                <div class="pill-container me-1 mb-1">
                  <span class="pill-font"> 💨 fan</span>
                </div>
              <% elsif appliance.kind == "charger"%>
                <div class="pill-container me-1 mb-1">
                  <span class="pill-font"> ⚡ 12V charger</span>
                </div>
              <% elsif appliance.kind == "pump"%>
                <div class="pill-container me-1 mb-1">
                  <span class="pill-font"> 💧 water pump</span>
                </div>
              <% end %>
            <% end %>
          </div>
          <div class="appliances-text d-flex border-top card-bottom-boxes-position w-100">
            <div class="d-flex flex-column w-100 right-border ps-3">
              <p class="mb-2 pt-2">Daily Battery Usage</p>
              <p class="text-black"><strong><%= build.total_amp_hours.round(2) %> Ah</strong></p>
            </div>
            <div class="d-flex flex-column w-100 ps-3">
              <p class="mb-2 pt-2">Total Price</p>
              <p class="text-black"><strong>$<%= build.total_price %></strong></p>
            </div>
          </div>
        </div>
      <% end %>

app/views/shared/_builds_card.html.erb
<% @builds.each do |build| %>
        <%= link_to build_path(build), class: "text-decoration-none text-black", target: :_blank do %>
          <div class="builds-card-container-new card-shadow">
            <div class="d-flex justify-content-between">
              <div>
                <div class="build-title-new">
                  <p><strong><%= build.name %></strong></p>
                </div>
                <div class="build-price-new">
                  <p><strong>$<%= build.total_price %></strong></p>
                </div>
              </div>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/random", class: "avatar-large", alt: "avatar-large" %>
            </div>

            <div class="build-text-new">
              <p><strong>Capacity: </strong> <%= build.total_amp_hours %>Ah   /  <strong>Appliances: </strong><%= build.build_appliances.length %></p>
            </div>

            <div class="trio-line">
              <div class="d-flex justify-content-center container-trio-new">
                <%= image_tag("trio_2.png", :alt => "icons", style: 'width: 75%') %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid  m-0 p-0">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", alt: "Fusiovan"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "All Builds", builds_path, class: "nav-link" %>
          </li>
          <% if current_user.user_url?%>
            <li class="nav-item dropdown">
              <%= image_tag current_user.user_url,
              class: "avatar dropdown-toggle",
              id: "navbarDropdown",
              data: { bs_toggle: "dropdown" },
              'aria-haspopup': true,
              'aria-expanded': false %>
            <% else%>
              <li class="nav-item dropdown">
                <%= cl_image_tag current_user.photo.key,
                class: "avatar dropdown-toggle",
                id: "navbarDropdown",
                data: { bs_toggle: "dropdown" },
                'aria-haspopup': true,
                'aria-expanded': false %>
                <% end%>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_overview_card.html.erb
<div class="card-overview box-relative">
  <div class="d-flex justify-content-between">
    <h2 class="mb-0">Overview</h2>
    <% if @build.user.user_url != nil %>
    <%= image_tag @build.user.user_url, class: "avatar-large", alt: "avatar-large" %>
    <%  else %>
    <%= cl_image_tag @build.user.photo.key, class: "avatar-large", alt: "avatar-large"%>
    <% end%>
  </div>
  <h3 class="p-1 my-3"><strong>Appliances</strong></h3>
  <div class="d-flex mb-3" style="flex-wrap: wrap;">
    <% @build.appliances.each do |appliance| %>
      <% if appliance.kind == "inverter" %>
        <div class="pill-container me-1 mb-2">
          <span class="pill-font">🔌 inverter</span>
        </div>
      <% elsif appliance.kind == "lights"%>
        <div class="pill-container me-1 mb-2">
          <span class="pill-font">💡 lights</span>
        </div>
      <% elsif appliance.kind == "fridge"%>
        <div class="pill-container me-1 mb-2">
          <span class="pill-font">❄️ fridge</span>
        </div>
      <% elsif appliance.kind == "fan"%>
        <div class="pill-container me-1 mb-2">
          <span class="pill-font">💨 fan</span>
        </div>
      <% elsif appliance.kind == "pump"%>
        <div class="pill-container me-1 mb-2">
          <span class="pill-font">💧 Water pump</span>
        </div>
      <% elsif appliance.kind == "charger"%>
        <div class="pill-container me-1 mb-2">
          <span class="pill-font">⚡️ 12V charger</span>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="pill-grid pill-text mb-3">
    <% @build.appliances.pluck(:kind).each do |kind| %>
      <% if kind == "fridge" %>
        <p class="me-1 mb-1">❄️ <%= @build.fridge_use_hours.to_i %> hr = <%= @build.fridge_amp_hours.round(2) %> Ah</p>
      <% elsif kind == "inverter" %>
      <p class="me-1 mb-1">🔌  <%= @build.inverter_use_hours.to_i %> hr = <%= @build.inverter_amp_hours.round(2) %> Ah</p>
      <% elsif kind == "fan" %>
      <p class="me-1 mb-1">💨 <%= @build.fan_use_hours.to_i %> hr = <%= @build.fan_amp_hours.round(2) %> Ah</p>
      <% elsif kind == "lights" %>
      <p class="me-1 mb-1">💡 <%= @build.lights_use_hours.to_i %> hr = <%= @build.lights_amp_hours.round(2) %> Ah</p>
      <% elsif kind == "pump" %>
      <p class="me-1 mb-1">💧 <%= @build.pump_use_hours.to_i %> hr = <%= @build.pump_amp_hours.round(2) %> Ah</p>
      <% elsif kind == "charger" %>
      <p class="me-1 mb-1"> ⚡️ <%= @build.charger_use_hours.to_i %> hr = <%= @build.charger_amp_hours.round(2) %> Ah</p>
      <% end %>
    <% end %>
  </div>

  <div class="d-flex d-flex align-items-start flex-column bd-highlight">
    <div class="p-1 bd-highlight">
      <p class="mb-0">Total daily battery usage</p>
      <h5 class="mt-1"><%= @build.total_amp_hours %> Ah</h5>
    </div>

    <div class="p-1 bd-highlight">
      <%# <p class="mb-2"><strong>Battery</strong></p> %>
      <p class="mb-2">Battery</p>
       <strong> <p class="mb-2">🔋 <%= @build.battery.make %> <%= @build.battery.kind %>  |  <%= @build.battery.amp_hours %> Ah</p></strong>
    </div>
    <div class="p-1 bd-highlight">
      <%# <p class="mb-2"><strong>Solar Panel</strong></p> %>
      <p class="mb-2">Solar Panel</p>
       <strong> <p class="mb-2">☀️ <%= @build.solar_panel.make %> <%= @build.solar_panel.kind %> Mono |  <%= @build.solar_panel.watts %> Watts</p></strong>
    </div>

    <div class="d-flex border-top card-bottom-boxes-position w-100">
      <%# <div class="d-flex flex-column right-border ps-3" style="flex-grow: 1;width: 121%;">
        <p>Daily Build Capacity</p>
        <p class="small-text ">100 ah</p>
      </div> %>
      <div class="d-flex flex-column w-100 px-4 mb-4 mt-3">
        <p class="mb-0">Total price</p>
        <h3 class="mt-2">$<%= @build.set_total_price %></h3>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
    <div class="sidebar-header">
      <%= link_to root_path, class: "navbar-brand", data: { turbolinks: false } do %>
        <div class="sidebar-logo">
        <%= image_tag "logo.png", alt: "FusioVan Logo", height: 100 %>
        </div>

      <% end %>
      <h2 class= "text-justify">FusioVan</h2>
    </div>


    <ul class="sidebar-links">
    <li>
      <span class="material-symbols-outlined">home</span>
      <%= link_to "My Dashboard", dashboard_path, class: "d-block text-decoration-none text-start" %>
    </li>
    <li>
      <span class="material-symbols-outlined">explore</span>
      <%= link_to "Explore Builds", builds_path, class: "d-block text-decoration-none text-start" %>
    </li>
    <li>
      <span class="material-symbols-outlined">mode_fan</span>
      <%= link_to "Appliances", appliances_path, class: "d-block text-decoration-none text-start" %>
    </li>
    <li>
      <span class="material-symbols-outlined">dashboard</span>
      <%= link_to "Components", components_path, class: "d-block text-decoration-none text-start" %>
    </li>
    <li>
      <span class="material-symbols-outlined">build_circle</span>
      <%= link_to "Create a Build", new_build_path, class: "d-block text-decoration-none text-start" %>
    </li>
    </ul>

    <% if user_signed_in? %>
    <ul class="m-3 navbar-user-action">
      <li>
      <span class="material-symbols-outlined d-block text-decoration-none text-black text-align-center bottom-align-text">logout</span>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "d-block text-decoration-none text-align-center bottom-align-text" %>
      </li>
    </ul>
    <% else %>
      <div class="m-3 navbar-user-action">
        <%= link_to "Login", new_user_session_path, class: "d-block text-decoration-none text-black text-align-center bottom-align-text"%>
        <%= link_to "Sign up", new_user_registration_path, class: " d-block text-decoration-none text-black text-align-center bottom-align-text" %>
      </div>
    <% end %>

app/views/shared/_solar_panel_card.html.erb
<div class="builds-card-container">
          <div class="d-flex justify-content-between inner-space">
            <div>
              <div class="build-title">
                <p><strong><%= build.solar_panel.make %></strong></p>
              </div>
              <div class="build-model">
                <p><strong><%= build.solar_panel.model %></strong></p>
              </div>
              <div class="build-price">
                <p class="mt-3"><strong>$ <%= build.solar_panel.price %></strong></p>
              </div>
            </div>
            <%= image_tag "solar_panel_color.png" %>
          </div>
          <div class="build-text text-center mt-1">
            <p><strong>Volts:</strong> 12V   /  <strong>Amps:</strong> 0.5A</p>
          </div>
          <div class="build-link text-center mt-2">
            <a href="#">Go to product page</a>
          </div>
        </div>

app/views/shared/_solar_panel_card_redesigned.html.erb
<div class="builds-card-container-new card-shadow box-relative">
  <div class="d-flex justify-content-between">
    <div>
      <div class="build-title-new align-items-start flex-column">
        <p class="mb-2"><%= solar_panel.model %></p>
        <p class="appliances-text mb-1"><%= solar_panel.make %></p>
      </div>
    </div>
    <%= image_tag "new_solar_panel_#{solar_panel.model.gsub(/\s+/, "").downcase}.png", class: "solar_panel-img", class: "solar_panel-img" %>
  </div>
  <div class="d-flex mt-5">
    <span class="material-symbols-outlined" style="color: gray;">open_in_new</span>
    <a class="appliances-text mt-1" href="#" target="blank" class="appliances-text" style="text-decoration: none">Go to product page</a>
  </div>
  <div class="appliances-text d-flex border-top card-bottom-boxes-position w-100">
    <div class="d-flex flex-column w-100 right-border ps-3">
      <p class="mb-2 pt-2">Volts</p>
      <p class="text-black"><strong><%= solar_panel.voltage %> V</strong></p>
    </div>
    <div class="d-flex flex-column w-100 ps-3 right-border">
      <p class="mb-2 pt-2">Watts</p>
      <p class="text-black"><strong><%= solar_panel.watts %> W</p></strong>
    </div>
    <div class="d-flex flex-column w-100 ps-3">
      <p class="mb-2 pt-2">Price</p>
      <p class="text-black"><strong>$ <%= solar_panel.price %></p></strong>
    </div>
  </div>
</div>